### ISSUE TITLE
generic ConnectionPool

### ISSUE THREAD

**Issue by tanner0101** [vapor-community/nio-kit#19]
Vapor's DatabaseKit package contains a connection pool class for managing database connections. I think it could be useful to make that class more generic and move it here. That would allow for other connections, like HTTP client connections, to easily take advantage of pooling.

Here's an idea of what this might entail:

```swift
public protocol ConnectionPoolItem {
    var isClosed: Bool { get }
}
public protocol ConnectionPoolSource {
    associatedtype Connection: ConnectionPoolItem
    var eventLoop: EventLoop { get }
    func makeConnection() -> EventLoopFuture<Connection>
}

public struct ConnectionPoolConfig {
    var maxConnections: Int
}

public final class ConnectionPool<Source> where Source: ConnectionPoolSource  {
    init(config: ConnectionPoolConfig, source: Source) { ... }
    func requestConnection() -> EventLoopFuture<Source.Connection> { ... }
    func releaseConnection(_: Source.Connection)
}

extension ConnectionPool {
     func withConnection(_: (Source.Connection) -> EventLoopFuture<Void>) -> EventLoopFuture<Void> { ... }
}
```

**Comment by Mordil** [comment]
Do we know the SwiftNIO team's thoughts on this being baked in somehow to NIO itself?

Either way, I think it's extremely useful and might be one of the core features that drives adoption of this library
